### ISSUE TITLE
Send to multiple users or subscribe to topics?

### ISSUE THREAD

**Issue by pwFoo** [pmagaz/webpush-notification-server#1]
Is it possible to send notification to multiple users or subscribe different topics?

**Comment by pmagaz** [comment]
Hi,

Actually server will send notification to every user subscribed. Users subscriptions are stored in NeDB embebed database. You can easyly create differente topics passing the topic to /register endpoint and saving the topic as additional field. Then, when you want to send notifications for an especific topic, you have to query for subscriptions matching that topic. Take a look to (db/index.js)
